# https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings

version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"

python:
  install:
    - method: pip
      requirements: dev-requirements.txt
      extra_requirements:
        - furo

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/source/conf.py
