from .merging_easy_test import *
from .merging_one_ref import *
from .merging_subdoc import *
from .merging_remove import *
from .merging_check_invalid_subdoc import *
from .merging_check_ref_not_found import *
from .merging_multiple_files_same_repo import *
from .merging_three_repos import *
from .merging_relative_ref_in_repo import *
from .merging_check_infinite_recursion import *
from .negative_validation import *
from .variables import *
